[general]
# import = ["~/.config/alacritty/tokyonight_storm.toml",]
import = ["~/.config/alacritty/rose-pine-moon.toml",]

[env]
# TERM = "xterm-256color"

[window]
decorations = "Transparent"
# padding.x = 5
padding = { x = 5, y = 0 }
dynamic_padding = true
# BELOW IS IMPORTANT FOR REDUCING LAG ON MAC
# https://github.com/alacritty/alacritty/issues/4474
opacity = 0.99

[font]
# normal = { family = "FiraCode Nerd Font Mono" }
normal = { family = "Hack Nerd Font Mono" }
# size = 14

[mouse]
hide_when_typing = true
