import = ["~/.config/alacritty/tokyonight_storm.toml",]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
padding = { x = 6, y = 25 }
dynamic_padding = true
# BELOW IS IMPORTANT FOR REDUCING LAG ON MAC
# https://github.com/alacritty/alacritty/issues/4474
opacity = 0.99

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 16

[mouse]
hide_when_typing = true
